package de.powerizzle.musikster

import android.content.Context
import java.io.File
import java.util.zip.GZIPInputStream
import org.json.JSONObject

enum class DeckSource { Bundled, Imported }

/** A deck the app knows about, plus whether it's currently part of the game. */
data class LoadedDeck(val deck: Deck, val source: DeckSource, val enabled: Boolean) {
    val id: String get() = deck.deckId
}

sealed class DeckImportResult {
    data class Success(val deck: Deck, val replacedExisting: Boolean) : DeckImportResult()
    object Invalid : DeckImportResult()
}

/**
 * Holds every deck the app knows about and answers "which card is this?" for scans.
 *
 * Decks come from two places:
 *  - the one bundled at build time as assets/<slug>-deck.json.gz by this build's product flavor
 *    (see app/build.gradle.kts — one flavor per person, deck generated by
 *    scripts/build_deck.py, gitignored because it's someone's personal playlist);
 *  - any number imported at runtime via [importDeck] from the Home screen, stored under
 *    files/decks/. That's how someone with one person's build can add another person's deck
 *    and play both shuffled together — the game doesn't care which deck a card came from.
 *
 * Every deck can be toggled in or out of the game without deleting it. [findCard] only
 * searches enabled decks. An imported deck with the same id as the bundled one replaces
 * it (that's how an updated deck.json gets sent to someone without a rebuild).
 */
class DeckRepository(private val context: Context) {

    private val decksDir: File get() = File(context.filesDir, "decks")

    /** Pre-multi-deck installs kept their single imported deck here; migrated on first load. */
    private val legacyImportedFile: File get() = File(context.filesDir, "deck.json")

    private val prefs = context.getSharedPreferences("decks_prefs", Context.MODE_PRIVATE)

    // Decks only change through the mutating methods below, which all invalidate this;
    // loadDecks()/findCard() are called from the UI thread on every scan.
    @Volatile
    private var cache: List<LoadedDeck>? = null

    fun loadDecks(): List<LoadedDeck> {
        cache?.let { return it }
        synchronized(this) {
            return cache ?: readDecks().also { cache = it }
        }
    }

    fun enabledDecks(): List<LoadedDeck> = loadDecks().filter { it.enabled }

    fun hasPlayableDeck(): Boolean = enabledDecks().any { it.deck.cards.isNotEmpty() }

    /** First match wins if two enabled decks share a card id — see [conflictingCardIds]. */
    fun findCard(cardId: String): Card? =
        enabledDecks().firstNotNullOfOrNull { loaded -> loaded.deck.cards.find { it.cardId == cardId } }

    /**
     * Card ids present in more than one enabled deck. Only possible if two decks were
     * built without a card-id prefix (see [Card]); the Home screen warns about it since a
     * scan of such a card would silently play whichever deck is listed first.
     */
    fun conflictingCardIds(): Set<String> {
        val seen = HashSet<String>()
        val conflicts = HashSet<String>()
        enabledDecks().forEach { loaded ->
            loaded.deck.cards.forEach { card -> if (!seen.add(card.cardId)) conflicts.add(card.cardId) }
        }
        return conflicts
    }

    /**
     * Validates [bytes] parses as a [Deck], then persists it as an imported deck (enabled).
     * Transparently gzip-decompresses first if [bytes] looks gzipped (deck.json compresses
     * well — mostly repetitive keys/URLs — so it's small enough to email/AirDrop as a .gz).
     */
    fun importDeck(bytes: ByteArray): DeckImportResult {
        return try {
            val json = decode(bytes)
            val before = loadDecks()
            val deck = storeImported(JSONObject(json))
            setEnabled(deck.deckId, true) // also invalidates the cache
            DeckImportResult.Success(deck, replacedExisting = before.any { it.id == deck.deckId })
        } catch (e: Exception) {
            DeckImportResult.Invalid
        }
    }

    fun setEnabled(deckId: String, enabled: Boolean) {
        val disabled = disabledIds().toMutableSet()
        if (enabled) disabled.remove(deckId) else disabled.add(deckId)
        prefs.edit().putStringSet(KEY_DISABLED, disabled).apply()
        invalidate()
    }

    /** Deletes an imported deck. The bundled deck can only be disabled, not removed. */
    fun removeImported(deckId: String) {
        importedFile(deckId).delete()
        setEnabled(deckId, true) // don't leave a stale "disabled" entry behind
        invalidate()
    }

    // ---------------------------------------------------------------------------

    private fun invalidate() {
        synchronized(this) { cache = null }
    }

    private fun disabledIds(): Set<String> = prefs.getStringSet(KEY_DISABLED, emptySet()) ?: emptySet()

    private fun readDecks(): List<LoadedDeck> {
        migrateLegacyImport()
        val disabled = disabledIds()
        val bundled = readBundled()
        val imported = decksDir.listFiles { f -> f.isFile && f.extension == "json" }
            .orEmpty()
            .sortedBy { it.name }
            .mapNotNull { file -> parse(file.readText()) }
        val importedIds = imported.map { it.deckId }.toSet()

        val result = mutableListOf<LoadedDeck>()
        if (bundled != null && bundled.deckId !in importedIds) {
            result += LoadedDeck(bundled, DeckSource.Bundled, bundled.deckId !in disabled)
        }
        imported.forEach { result += LoadedDeck(it, DeckSource.Imported, it.deckId !in disabled) }
        return result
    }

    private fun parse(json: String): Deck? = try {
        Deck.fromJson(JSONObject(json))
    } catch (e: Exception) {
        null
    }

    /**
     * Writes an imported deck to files/decks/<id>.json, stamping the resolved deck id and
     * name into the JSON so a legacy file (no deckId) gets a stable identity. A legacy
     * file for the same playlist as the bundled deck adopts the bundled deck's id, so an
     * old install that had imported its own deck doesn't end up with two copies of it.
     */
    private fun storeImported(json: JSONObject): Deck {
        var deck = Deck.fromJson(json)
        if (!json.has("deckId")) {
            val bundled = readBundled()
            if (bundled != null && bundled.playlistId == deck.playlistId) {
                deck = deck.copy(deckId = bundled.deckId, name = bundled.name)
            }
        }
        json.put("deckId", deck.deckId)
        json.put("name", deck.name)
        decksDir.mkdirs()
        importedFile(deck.deckId).writeText(json.toString(2))
        return deck
    }

    private fun migrateLegacyImport() {
        val file = legacyImportedFile
        if (!file.exists()) return
        try {
            storeImported(JSONObject(file.readText()))
        } catch (e: Exception) {
            // Unreadable legacy file — nothing worth keeping.
        }
        file.delete()
    }

    private fun importedFile(deckId: String): File =
        File(decksDir, deckId.replace(Regex("[^A-Za-z0-9_-]"), "_") + ".json")

    /** The deck JSON in [bytes], gunzipped first if it's gzip data (plain JSON passes through). */
    private fun decode(bytes: ByteArray): String =
        (if (isGzip(bytes)) GZIPInputStream(bytes.inputStream()) else bytes.inputStream())
            .bufferedReader().use { it.readText() }

    private fun isGzip(bytes: ByteArray): Boolean =
        bytes.size >= 2 && bytes[0] == 0x1f.toByte() && bytes[1] == 0x8b.toByte()

    /**
     * The flavor's bundled deck: scripts/build_deck.py writes it as <slug>-deck.json.gz (the same
     * file that gets sent around for Import Deck). Android's asset packaging unpacks .gz assets
     * and drops the extension, so in the APK it's usually a plain <slug>-deck.json; an older
     * build's deck.json works too. Null for builds without one (the generic flavor, "bundleDeck": false).
     */
    private fun readBundled(): Deck? = try {
        val name = context.assets.list("").orEmpty().firstOrNull {
            it.endsWith("-deck.json.gz") || it.endsWith("-deck.json") || it == "deck.json"
        }
        name?.let { context.assets.open(it).use { input -> parse(decode(input.readBytes())) } }
    } catch (e: Exception) {
        null
    }

    private companion object {
        const val KEY_DISABLED = "disabled_deck_ids"
    }
}
